services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
  demo-one:
    container_name: demo-one
    image: 170042060/demo-one
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/amigosecode
    ports:
      - "7777:9090"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: