name: CI - Build Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - back-end/**
  pull_request:
    branches: [ "main" ]
    paths:
      - back-end/**

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.1
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: block_craft
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./back-end
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build and run Unit/Integration Tests with Maven
        run: ./mvnw clean verify -Ptest -DskipDockerBuild=true